---
abstract: 'Arbitrary sized integers having arbitrary charsets to calculate with key rooms'
author:
  - 'Tels <nospam-abuse@bloodgate.com>'
build_requires:
  Test::More: 0.62
distribution_type: module
generated_by: 'Module::Install version 0.71'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Math-String
no_index:
  directory:
    - bench
    - inc
    - t
requires:
  Math::BigFloat: 1.58
  Math::BigInt: 1.87
version: 1.28
