--- #YAML:1.0
name: Math-String
version: 1.27
version_from: lib/Math/String.pm
license: perl
distribution_type: module
generated_by: Math-String version 1.27
installdirs: site
requires:
  Math::BigFloat: 1.48
  Math::BigInt: 1.74
