# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-String
version:      1.25
version_from: lib/Math/String.pm
installdirs:  site
license:      perl
requires:
    Math::BigFloat:                1.47
    Math::BigInt:                  1.73

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
